services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres_payment
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=payments
    # env_file:
    #   - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  postgres:
